// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using UnityEngine;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameSessionModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public GameSessionModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<RedGaint.Network.GameSessionModule.SessionResponse> StartOrJoinSession(RedGaint.Network.GameSessionModule.SessionRequest request)
        {
            Debug.Log($"StartOrJoinSession got REquest :{request.PlayerName}: {request.PlayerId} : {request.CharacterId } : {request.Xp}");
            return await k_Service.CallModuleEndpointAsync<RedGaint.Network.GameSessionModule.SessionResponse>(
                "GameSessionModule",
                "StartOrJoinSession",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<List<RedGaint.Network.GameSessionModule.PlayerSummary>> GetLobbyPlayers(RedGaint.Network.GameSessionModule.LobbyRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<List<RedGaint.Network.GameSessionModule.PlayerSummary>>(
                "GameSessionModule",
                "GetLobbyPlayers",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<string> EndGameSession(RedGaint.Network.GameSessionModule.LobbyRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "EndGameSession",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<RedGaint.Network.GameSessionModule.ServerAllocationResult> GetServerDetails(RedGaint.Network.GameSessionModule.LobbyRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<RedGaint.Network.GameSessionModule.ServerAllocationResult>(
                "GameSessionModule",
                "GetServerDetails",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<string> ReleaseServer(RedGaint.Network.GameSessionModule.LobbyRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "ReleaseServer",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<string> GetAllocationServerLogs()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "GetAllocationServerLogs",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> ClearAllocationServerLogs()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "ClearAllocationServerLogs",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
