// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameSessionModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public GameSessionModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SayHello(string name)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"name", name},
                });
        }

        public async Task<RedGaint.Network.GameSessionModule.GameSession_SessionResponse> StartOrJoinSession(RedGaint.Network.GameSessionModule.GameSession_SessionRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<RedGaint.Network.GameSessionModule.GameSession_SessionResponse>(
                "GameSessionModule",
                "StartOrJoinSession",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }
    }
}
