// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameSessionModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public GameSessionModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<RedGaint.Network.GameSessionModule.SessionResponse> StartOrJoinSession(RedGaint.Network.GameSessionModule.SessionRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<RedGaint.Network.GameSessionModule.SessionResponse>(
                "GameSessionModule",
                "StartOrJoinSession",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<List<RedGaint.Network.GameSessionModule.PlayerSummary>> GetLobbyPlayers(RedGaint.Network.GameSessionModule.LobbyRequest request)
        {
            return await k_Service.CallModuleEndpointAsync<List<RedGaint.Network.GameSessionModule.PlayerSummary>>(
                "GameSessionModule",
                "GetLobbyPlayers",
                new Dictionary<string, object>()
                {
                    {"request", request},
                });
        }

        public async Task<string> GetDebugLog()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "GetDebugLog",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> ClearDebugLog()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "GameSessionModule",
                "ClearDebugLog",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
