// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.RedGaint.Network.GameSessionModule
{
    public partial class ServerAllocationResult
    {
        public string AllocationId;
        public long ServerId;
        public string Ipv4;
        public string Ipv6;
        public int GamePort;
        public string LobbyId;

        [Preserve]
        public ServerAllocationResult ()
        {
        }
    }
}