// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.RedGaint.Network.GameSessionModule
{
    public partial class PlayerSummary
    {
        public string PlayerId;
        public string DisplayName;
        public string SelectedCharacterId;
        public bool IsLobbyReady;
        public int JoinOrder;
        public int MaxPlayersAllowed;

        [Preserve]
        public PlayerSummary ()
        {
        }
    }
}