// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.RedGaint.Network.GameSessionModule
{
    public partial class SessionRequest
    {
        public string PlayerId;
        public string CharacterId;
        public string PlayerName;
        public int Xp;

        [Preserve]
        public SessionRequest ()
        {
        }
    }
}