// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.RedGaint.Network.GameSessionModule
{
    public partial class LobbyRequest
    {
        public string lobbyId;

        [Preserve]
        public LobbyRequest ()
        {
        }
    }
}