// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.RedGaint.Network.GameSessionModule
{
    public partial class GameSession_SessionResponse
    {
        public string LobbyId;
        public string LobbyName;
        public string Message;

        [Preserve]
        public GameSession_SessionResponse ()
        {
        }
    }
}